plugins {
    id 'java-library'
}

group = 'com.github.mjacques.fdeb'
version = '0.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    api 'org.locationtech.jts:jts-core:1.20.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.25.3'
}

tasks.named('test') {
    useJUnitPlatform()
    jvmArgs '-Xmx2g'
}
